# This is a basic workflow to help you get started with Actions
name: Deploy to production
# Controls when the workflow will run
on:
  # Runs on the push to the develop branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # setup the node development environment
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install all dependencies
        run: npm install

      # Runs a set of commands using the runners shell
      # to added after the merge of test PR
      - name: Run a test
        run: npm run test
  deploy:
    # deploy to heroku dev pipeline
    concurrency: 
      group: heroku_deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: production
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "phantom-codebandits-pro"
          heroku_email: "tumbafabruce@gmail.com"
          
